include:
  - project: infra/gitlab-ci-templates
    ref: main
    file:
      # utilities
      - base/stages.yml
      - base/defaults.yml
      - base/rules.yml
      - notify/ci-slack-notification.yml
      # test-and-build stage
      - lint/go-lint.yml
      - test/go-test-coverage.yml

workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" || $CI_COMMIT_BRANCH == "main"'
      when: always
    - when: never

lint:
  extends: .go_lint

go_test_with_coverage:
  extends: .go_test_with_coverage
