// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/flexprice/flexprice/ent/predicate"
	"github.com/flexprice/flexprice/ent/systemevent"
)

// SystemEventQuery is the builder for querying SystemEvent entities.
type SystemEventQuery struct {
	config
	ctx        *QueryContext
	order      []systemevent.OrderOption
	inters     []Interceptor
	predicates []predicate.SystemEvent
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the SystemEventQuery builder.
func (seq *SystemEventQuery) Where(ps ...predicate.SystemEvent) *SystemEventQuery {
	seq.predicates = append(seq.predicates, ps...)
	return seq
}

// Limit the number of records to be returned by this query.
func (seq *SystemEventQuery) Limit(limit int) *SystemEventQuery {
	seq.ctx.Limit = &limit
	return seq
}

// Offset to start from.
func (seq *SystemEventQuery) Offset(offset int) *SystemEventQuery {
	seq.ctx.Offset = &offset
	return seq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (seq *SystemEventQuery) Unique(unique bool) *SystemEventQuery {
	seq.ctx.Unique = &unique
	return seq
}

// Order specifies how the records should be ordered.
func (seq *SystemEventQuery) Order(o ...systemevent.OrderOption) *SystemEventQuery {
	seq.order = append(seq.order, o...)
	return seq
}

// First returns the first SystemEvent entity from the query.
// Returns a *NotFoundError when no SystemEvent was found.
func (seq *SystemEventQuery) First(ctx context.Context) (*SystemEvent, error) {
	nodes, err := seq.Limit(1).All(setContextOp(ctx, seq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{systemevent.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (seq *SystemEventQuery) FirstX(ctx context.Context) *SystemEvent {
	node, err := seq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first SystemEvent ID from the query.
// Returns a *NotFoundError when no SystemEvent ID was found.
func (seq *SystemEventQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = seq.Limit(1).IDs(setContextOp(ctx, seq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{systemevent.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (seq *SystemEventQuery) FirstIDX(ctx context.Context) string {
	id, err := seq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single SystemEvent entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one SystemEvent entity is found.
// Returns a *NotFoundError when no SystemEvent entities are found.
func (seq *SystemEventQuery) Only(ctx context.Context) (*SystemEvent, error) {
	nodes, err := seq.Limit(2).All(setContextOp(ctx, seq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{systemevent.Label}
	default:
		return nil, &NotSingularError{systemevent.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (seq *SystemEventQuery) OnlyX(ctx context.Context) *SystemEvent {
	node, err := seq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only SystemEvent ID in the query.
// Returns a *NotSingularError when more than one SystemEvent ID is found.
// Returns a *NotFoundError when no entities are found.
func (seq *SystemEventQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = seq.Limit(2).IDs(setContextOp(ctx, seq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{systemevent.Label}
	default:
		err = &NotSingularError{systemevent.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (seq *SystemEventQuery) OnlyIDX(ctx context.Context) string {
	id, err := seq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of SystemEvents.
func (seq *SystemEventQuery) All(ctx context.Context) ([]*SystemEvent, error) {
	ctx = setContextOp(ctx, seq.ctx, ent.OpQueryAll)
	if err := seq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*SystemEvent, *SystemEventQuery]()
	return withInterceptors[[]*SystemEvent](ctx, seq, qr, seq.inters)
}

// AllX is like All, but panics if an error occurs.
func (seq *SystemEventQuery) AllX(ctx context.Context) []*SystemEvent {
	nodes, err := seq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of SystemEvent IDs.
func (seq *SystemEventQuery) IDs(ctx context.Context) (ids []string, err error) {
	if seq.ctx.Unique == nil && seq.path != nil {
		seq.Unique(true)
	}
	ctx = setContextOp(ctx, seq.ctx, ent.OpQueryIDs)
	if err = seq.Select(systemevent.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (seq *SystemEventQuery) IDsX(ctx context.Context) []string {
	ids, err := seq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (seq *SystemEventQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, seq.ctx, ent.OpQueryCount)
	if err := seq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, seq, querierCount[*SystemEventQuery](), seq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (seq *SystemEventQuery) CountX(ctx context.Context) int {
	count, err := seq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (seq *SystemEventQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, seq.ctx, ent.OpQueryExist)
	switch _, err := seq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (seq *SystemEventQuery) ExistX(ctx context.Context) bool {
	exist, err := seq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the SystemEventQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (seq *SystemEventQuery) Clone() *SystemEventQuery {
	if seq == nil {
		return nil
	}
	return &SystemEventQuery{
		config:     seq.config,
		ctx:        seq.ctx.Clone(),
		order:      append([]systemevent.OrderOption{}, seq.order...),
		inters:     append([]Interceptor{}, seq.inters...),
		predicates: append([]predicate.SystemEvent{}, seq.predicates...),
		// clone intermediate query.
		sql:  seq.sql.Clone(),
		path: seq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		TenantID string `json:"tenant_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.SystemEvent.Query().
//		GroupBy(systemevent.FieldTenantID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (seq *SystemEventQuery) GroupBy(field string, fields ...string) *SystemEventGroupBy {
	seq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &SystemEventGroupBy{build: seq}
	grbuild.flds = &seq.ctx.Fields
	grbuild.label = systemevent.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		TenantID string `json:"tenant_id,omitempty"`
//	}
//
//	client.SystemEvent.Query().
//		Select(systemevent.FieldTenantID).
//		Scan(ctx, &v)
func (seq *SystemEventQuery) Select(fields ...string) *SystemEventSelect {
	seq.ctx.Fields = append(seq.ctx.Fields, fields...)
	sbuild := &SystemEventSelect{SystemEventQuery: seq}
	sbuild.label = systemevent.Label
	sbuild.flds, sbuild.scan = &seq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a SystemEventSelect configured with the given aggregations.
func (seq *SystemEventQuery) Aggregate(fns ...AggregateFunc) *SystemEventSelect {
	return seq.Select().Aggregate(fns...)
}

func (seq *SystemEventQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range seq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, seq); err != nil {
				return err
			}
		}
	}
	for _, f := range seq.ctx.Fields {
		if !systemevent.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if seq.path != nil {
		prev, err := seq.path(ctx)
		if err != nil {
			return err
		}
		seq.sql = prev
	}
	return nil
}

func (seq *SystemEventQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*SystemEvent, error) {
	var (
		nodes = []*SystemEvent{}
		_spec = seq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*SystemEvent).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &SystemEvent{config: seq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, seq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (seq *SystemEventQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := seq.querySpec()
	_spec.Node.Columns = seq.ctx.Fields
	if len(seq.ctx.Fields) > 0 {
		_spec.Unique = seq.ctx.Unique != nil && *seq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, seq.driver, _spec)
}

func (seq *SystemEventQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(systemevent.Table, systemevent.Columns, sqlgraph.NewFieldSpec(systemevent.FieldID, field.TypeString))
	_spec.From = seq.sql
	if unique := seq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if seq.path != nil {
		_spec.Unique = true
	}
	if fields := seq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, systemevent.FieldID)
		for i := range fields {
			if fields[i] != systemevent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := seq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := seq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := seq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := seq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (seq *SystemEventQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(seq.driver.Dialect())
	t1 := builder.Table(systemevent.Table)
	columns := seq.ctx.Fields
	if len(columns) == 0 {
		columns = systemevent.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if seq.sql != nil {
		selector = seq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if seq.ctx.Unique != nil && *seq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range seq.predicates {
		p(selector)
	}
	for _, p := range seq.order {
		p(selector)
	}
	if offset := seq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := seq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// SystemEventGroupBy is the group-by builder for SystemEvent entities.
type SystemEventGroupBy struct {
	selector
	build *SystemEventQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (segb *SystemEventGroupBy) Aggregate(fns ...AggregateFunc) *SystemEventGroupBy {
	segb.fns = append(segb.fns, fns...)
	return segb
}

// Scan applies the selector query and scans the result into the given value.
func (segb *SystemEventGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, segb.build.ctx, ent.OpQueryGroupBy)
	if err := segb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SystemEventQuery, *SystemEventGroupBy](ctx, segb.build, segb, segb.build.inters, v)
}

func (segb *SystemEventGroupBy) sqlScan(ctx context.Context, root *SystemEventQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(segb.fns))
	for _, fn := range segb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*segb.flds)+len(segb.fns))
		for _, f := range *segb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*segb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := segb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// SystemEventSelect is the builder for selecting fields of SystemEvent entities.
type SystemEventSelect struct {
	*SystemEventQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ses *SystemEventSelect) Aggregate(fns ...AggregateFunc) *SystemEventSelect {
	ses.fns = append(ses.fns, fns...)
	return ses
}

// Scan applies the selector query and scans the result into the given value.
func (ses *SystemEventSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ses.ctx, ent.OpQuerySelect)
	if err := ses.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SystemEventQuery, *SystemEventSelect](ctx, ses.SystemEventQuery, ses, ses.inters, v)
}

func (ses *SystemEventSelect) sqlScan(ctx context.Context, root *SystemEventQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ses.fns))
	for _, fn := range ses.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ses.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ses.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
