// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/flexprice/flexprice/ent/predicate"
	"github.com/flexprice/flexprice/ent/systemevent"
)

// SystemEventUpdate is the builder for updating SystemEvent entities.
type SystemEventUpdate struct {
	config
	hooks    []Hook
	mutation *SystemEventMutation
}

// Where appends a list predicates to the SystemEventUpdate builder.
func (seu *SystemEventUpdate) Where(ps ...predicate.SystemEvent) *SystemEventUpdate {
	seu.mutation.Where(ps...)
	return seu
}

// SetStatus sets the "status" field.
func (seu *SystemEventUpdate) SetStatus(s string) *SystemEventUpdate {
	seu.mutation.SetStatus(s)
	return seu
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (seu *SystemEventUpdate) SetNillableStatus(s *string) *SystemEventUpdate {
	if s != nil {
		seu.SetStatus(*s)
	}
	return seu
}

// SetUpdatedAt sets the "updated_at" field.
func (seu *SystemEventUpdate) SetUpdatedAt(t time.Time) *SystemEventUpdate {
	seu.mutation.SetUpdatedAt(t)
	return seu
}

// SetUpdatedBy sets the "updated_by" field.
func (seu *SystemEventUpdate) SetUpdatedBy(s string) *SystemEventUpdate {
	seu.mutation.SetUpdatedBy(s)
	return seu
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (seu *SystemEventUpdate) SetNillableUpdatedBy(s *string) *SystemEventUpdate {
	if s != nil {
		seu.SetUpdatedBy(*s)
	}
	return seu
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (seu *SystemEventUpdate) ClearUpdatedBy() *SystemEventUpdate {
	seu.mutation.ClearUpdatedBy()
	return seu
}

// SetEventName sets the "event_name" field.
func (seu *SystemEventUpdate) SetEventName(s string) *SystemEventUpdate {
	seu.mutation.SetEventName(s)
	return seu
}

// SetNillableEventName sets the "event_name" field if the given value is not nil.
func (seu *SystemEventUpdate) SetNillableEventName(s *string) *SystemEventUpdate {
	if s != nil {
		seu.SetEventName(*s)
	}
	return seu
}

// ClearEventName clears the value of the "event_name" field.
func (seu *SystemEventUpdate) ClearEventName() *SystemEventUpdate {
	seu.mutation.ClearEventName()
	return seu
}

// SetEntityType sets the "entity_type" field.
func (seu *SystemEventUpdate) SetEntityType(s string) *SystemEventUpdate {
	seu.mutation.SetEntityType(s)
	return seu
}

// SetNillableEntityType sets the "entity_type" field if the given value is not nil.
func (seu *SystemEventUpdate) SetNillableEntityType(s *string) *SystemEventUpdate {
	if s != nil {
		seu.SetEntityType(*s)
	}
	return seu
}

// ClearEntityType clears the value of the "entity_type" field.
func (seu *SystemEventUpdate) ClearEntityType() *SystemEventUpdate {
	seu.mutation.ClearEntityType()
	return seu
}

// SetEntityID sets the "entity_id" field.
func (seu *SystemEventUpdate) SetEntityID(s string) *SystemEventUpdate {
	seu.mutation.SetEntityID(s)
	return seu
}

// SetNillableEntityID sets the "entity_id" field if the given value is not nil.
func (seu *SystemEventUpdate) SetNillableEntityID(s *string) *SystemEventUpdate {
	if s != nil {
		seu.SetEntityID(*s)
	}
	return seu
}

// ClearEntityID clears the value of the "entity_id" field.
func (seu *SystemEventUpdate) ClearEntityID() *SystemEventUpdate {
	seu.mutation.ClearEntityID()
	return seu
}

// SetWebhookMessageID sets the "webhook_message_id" field.
func (seu *SystemEventUpdate) SetWebhookMessageID(s string) *SystemEventUpdate {
	seu.mutation.SetWebhookMessageID(s)
	return seu
}

// SetNillableWebhookMessageID sets the "webhook_message_id" field if the given value is not nil.
func (seu *SystemEventUpdate) SetNillableWebhookMessageID(s *string) *SystemEventUpdate {
	if s != nil {
		seu.SetWebhookMessageID(*s)
	}
	return seu
}

// ClearWebhookMessageID clears the value of the "webhook_message_id" field.
func (seu *SystemEventUpdate) ClearWebhookMessageID() *SystemEventUpdate {
	seu.mutation.ClearWebhookMessageID()
	return seu
}

// SetPublishedAt sets the "published_at" field.
func (seu *SystemEventUpdate) SetPublishedAt(t time.Time) *SystemEventUpdate {
	seu.mutation.SetPublishedAt(t)
	return seu
}

// SetNillablePublishedAt sets the "published_at" field if the given value is not nil.
func (seu *SystemEventUpdate) SetNillablePublishedAt(t *time.Time) *SystemEventUpdate {
	if t != nil {
		seu.SetPublishedAt(*t)
	}
	return seu
}

// ClearPublishedAt clears the value of the "published_at" field.
func (seu *SystemEventUpdate) ClearPublishedAt() *SystemEventUpdate {
	seu.mutation.ClearPublishedAt()
	return seu
}

// SetPayload sets the "payload" field.
func (seu *SystemEventUpdate) SetPayload(m map[string]interface{}) *SystemEventUpdate {
	seu.mutation.SetPayload(m)
	return seu
}

// ClearPayload clears the value of the "payload" field.
func (seu *SystemEventUpdate) ClearPayload() *SystemEventUpdate {
	seu.mutation.ClearPayload()
	return seu
}

// SetFailureCount sets the "failure_count" field.
func (seu *SystemEventUpdate) SetFailureCount(i int) *SystemEventUpdate {
	seu.mutation.ResetFailureCount()
	seu.mutation.SetFailureCount(i)
	return seu
}

// SetNillableFailureCount sets the "failure_count" field if the given value is not nil.
func (seu *SystemEventUpdate) SetNillableFailureCount(i *int) *SystemEventUpdate {
	if i != nil {
		seu.SetFailureCount(*i)
	}
	return seu
}

// AddFailureCount adds i to the "failure_count" field.
func (seu *SystemEventUpdate) AddFailureCount(i int) *SystemEventUpdate {
	seu.mutation.AddFailureCount(i)
	return seu
}

// SetFailureReason sets the "failure_reason" field.
func (seu *SystemEventUpdate) SetFailureReason(s string) *SystemEventUpdate {
	seu.mutation.SetFailureReason(s)
	return seu
}

// SetNillableFailureReason sets the "failure_reason" field if the given value is not nil.
func (seu *SystemEventUpdate) SetNillableFailureReason(s *string) *SystemEventUpdate {
	if s != nil {
		seu.SetFailureReason(*s)
	}
	return seu
}

// ClearFailureReason clears the value of the "failure_reason" field.
func (seu *SystemEventUpdate) ClearFailureReason() *SystemEventUpdate {
	seu.mutation.ClearFailureReason()
	return seu
}

// Mutation returns the SystemEventMutation object of the builder.
func (seu *SystemEventUpdate) Mutation() *SystemEventMutation {
	return seu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (seu *SystemEventUpdate) Save(ctx context.Context) (int, error) {
	seu.defaults()
	return withHooks(ctx, seu.sqlSave, seu.mutation, seu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (seu *SystemEventUpdate) SaveX(ctx context.Context) int {
	affected, err := seu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (seu *SystemEventUpdate) Exec(ctx context.Context) error {
	_, err := seu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (seu *SystemEventUpdate) ExecX(ctx context.Context) {
	if err := seu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (seu *SystemEventUpdate) defaults() {
	if _, ok := seu.mutation.UpdatedAt(); !ok {
		v := systemevent.UpdateDefaultUpdatedAt()
		seu.mutation.SetUpdatedAt(v)
	}
}

func (seu *SystemEventUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(systemevent.Table, systemevent.Columns, sqlgraph.NewFieldSpec(systemevent.FieldID, field.TypeString))
	if ps := seu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := seu.mutation.Status(); ok {
		_spec.SetField(systemevent.FieldStatus, field.TypeString, value)
	}
	if value, ok := seu.mutation.UpdatedAt(); ok {
		_spec.SetField(systemevent.FieldUpdatedAt, field.TypeTime, value)
	}
	if seu.mutation.CreatedByCleared() {
		_spec.ClearField(systemevent.FieldCreatedBy, field.TypeString)
	}
	if value, ok := seu.mutation.UpdatedBy(); ok {
		_spec.SetField(systemevent.FieldUpdatedBy, field.TypeString, value)
	}
	if seu.mutation.UpdatedByCleared() {
		_spec.ClearField(systemevent.FieldUpdatedBy, field.TypeString)
	}
	if seu.mutation.EnvironmentIDCleared() {
		_spec.ClearField(systemevent.FieldEnvironmentID, field.TypeString)
	}
	if value, ok := seu.mutation.EventName(); ok {
		_spec.SetField(systemevent.FieldEventName, field.TypeString, value)
	}
	if seu.mutation.EventNameCleared() {
		_spec.ClearField(systemevent.FieldEventName, field.TypeString)
	}
	if value, ok := seu.mutation.EntityType(); ok {
		_spec.SetField(systemevent.FieldEntityType, field.TypeString, value)
	}
	if seu.mutation.EntityTypeCleared() {
		_spec.ClearField(systemevent.FieldEntityType, field.TypeString)
	}
	if value, ok := seu.mutation.EntityID(); ok {
		_spec.SetField(systemevent.FieldEntityID, field.TypeString, value)
	}
	if seu.mutation.EntityIDCleared() {
		_spec.ClearField(systemevent.FieldEntityID, field.TypeString)
	}
	if value, ok := seu.mutation.WebhookMessageID(); ok {
		_spec.SetField(systemevent.FieldWebhookMessageID, field.TypeString, value)
	}
	if seu.mutation.WebhookMessageIDCleared() {
		_spec.ClearField(systemevent.FieldWebhookMessageID, field.TypeString)
	}
	if value, ok := seu.mutation.PublishedAt(); ok {
		_spec.SetField(systemevent.FieldPublishedAt, field.TypeTime, value)
	}
	if seu.mutation.PublishedAtCleared() {
		_spec.ClearField(systemevent.FieldPublishedAt, field.TypeTime)
	}
	if value, ok := seu.mutation.Payload(); ok {
		_spec.SetField(systemevent.FieldPayload, field.TypeJSON, value)
	}
	if seu.mutation.PayloadCleared() {
		_spec.ClearField(systemevent.FieldPayload, field.TypeJSON)
	}
	if value, ok := seu.mutation.FailureCount(); ok {
		_spec.SetField(systemevent.FieldFailureCount, field.TypeInt, value)
	}
	if value, ok := seu.mutation.AddedFailureCount(); ok {
		_spec.AddField(systemevent.FieldFailureCount, field.TypeInt, value)
	}
	if value, ok := seu.mutation.FailureReason(); ok {
		_spec.SetField(systemevent.FieldFailureReason, field.TypeString, value)
	}
	if seu.mutation.FailureReasonCleared() {
		_spec.ClearField(systemevent.FieldFailureReason, field.TypeString)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, seu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{systemevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	seu.mutation.done = true
	return n, nil
}

// SystemEventUpdateOne is the builder for updating a single SystemEvent entity.
type SystemEventUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SystemEventMutation
}

// SetStatus sets the "status" field.
func (seuo *SystemEventUpdateOne) SetStatus(s string) *SystemEventUpdateOne {
	seuo.mutation.SetStatus(s)
	return seuo
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (seuo *SystemEventUpdateOne) SetNillableStatus(s *string) *SystemEventUpdateOne {
	if s != nil {
		seuo.SetStatus(*s)
	}
	return seuo
}

// SetUpdatedAt sets the "updated_at" field.
func (seuo *SystemEventUpdateOne) SetUpdatedAt(t time.Time) *SystemEventUpdateOne {
	seuo.mutation.SetUpdatedAt(t)
	return seuo
}

// SetUpdatedBy sets the "updated_by" field.
func (seuo *SystemEventUpdateOne) SetUpdatedBy(s string) *SystemEventUpdateOne {
	seuo.mutation.SetUpdatedBy(s)
	return seuo
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (seuo *SystemEventUpdateOne) SetNillableUpdatedBy(s *string) *SystemEventUpdateOne {
	if s != nil {
		seuo.SetUpdatedBy(*s)
	}
	return seuo
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (seuo *SystemEventUpdateOne) ClearUpdatedBy() *SystemEventUpdateOne {
	seuo.mutation.ClearUpdatedBy()
	return seuo
}

// SetEventName sets the "event_name" field.
func (seuo *SystemEventUpdateOne) SetEventName(s string) *SystemEventUpdateOne {
	seuo.mutation.SetEventName(s)
	return seuo
}

// SetNillableEventName sets the "event_name" field if the given value is not nil.
func (seuo *SystemEventUpdateOne) SetNillableEventName(s *string) *SystemEventUpdateOne {
	if s != nil {
		seuo.SetEventName(*s)
	}
	return seuo
}

// ClearEventName clears the value of the "event_name" field.
func (seuo *SystemEventUpdateOne) ClearEventName() *SystemEventUpdateOne {
	seuo.mutation.ClearEventName()
	return seuo
}

// SetEntityType sets the "entity_type" field.
func (seuo *SystemEventUpdateOne) SetEntityType(s string) *SystemEventUpdateOne {
	seuo.mutation.SetEntityType(s)
	return seuo
}

// SetNillableEntityType sets the "entity_type" field if the given value is not nil.
func (seuo *SystemEventUpdateOne) SetNillableEntityType(s *string) *SystemEventUpdateOne {
	if s != nil {
		seuo.SetEntityType(*s)
	}
	return seuo
}

// ClearEntityType clears the value of the "entity_type" field.
func (seuo *SystemEventUpdateOne) ClearEntityType() *SystemEventUpdateOne {
	seuo.mutation.ClearEntityType()
	return seuo
}

// SetEntityID sets the "entity_id" field.
func (seuo *SystemEventUpdateOne) SetEntityID(s string) *SystemEventUpdateOne {
	seuo.mutation.SetEntityID(s)
	return seuo
}

// SetNillableEntityID sets the "entity_id" field if the given value is not nil.
func (seuo *SystemEventUpdateOne) SetNillableEntityID(s *string) *SystemEventUpdateOne {
	if s != nil {
		seuo.SetEntityID(*s)
	}
	return seuo
}

// ClearEntityID clears the value of the "entity_id" field.
func (seuo *SystemEventUpdateOne) ClearEntityID() *SystemEventUpdateOne {
	seuo.mutation.ClearEntityID()
	return seuo
}

// SetWebhookMessageID sets the "webhook_message_id" field.
func (seuo *SystemEventUpdateOne) SetWebhookMessageID(s string) *SystemEventUpdateOne {
	seuo.mutation.SetWebhookMessageID(s)
	return seuo
}

// SetNillableWebhookMessageID sets the "webhook_message_id" field if the given value is not nil.
func (seuo *SystemEventUpdateOne) SetNillableWebhookMessageID(s *string) *SystemEventUpdateOne {
	if s != nil {
		seuo.SetWebhookMessageID(*s)
	}
	return seuo
}

// ClearWebhookMessageID clears the value of the "webhook_message_id" field.
func (seuo *SystemEventUpdateOne) ClearWebhookMessageID() *SystemEventUpdateOne {
	seuo.mutation.ClearWebhookMessageID()
	return seuo
}

// SetPublishedAt sets the "published_at" field.
func (seuo *SystemEventUpdateOne) SetPublishedAt(t time.Time) *SystemEventUpdateOne {
	seuo.mutation.SetPublishedAt(t)
	return seuo
}

// SetNillablePublishedAt sets the "published_at" field if the given value is not nil.
func (seuo *SystemEventUpdateOne) SetNillablePublishedAt(t *time.Time) *SystemEventUpdateOne {
	if t != nil {
		seuo.SetPublishedAt(*t)
	}
	return seuo
}

// ClearPublishedAt clears the value of the "published_at" field.
func (seuo *SystemEventUpdateOne) ClearPublishedAt() *SystemEventUpdateOne {
	seuo.mutation.ClearPublishedAt()
	return seuo
}

// SetPayload sets the "payload" field.
func (seuo *SystemEventUpdateOne) SetPayload(m map[string]interface{}) *SystemEventUpdateOne {
	seuo.mutation.SetPayload(m)
	return seuo
}

// ClearPayload clears the value of the "payload" field.
func (seuo *SystemEventUpdateOne) ClearPayload() *SystemEventUpdateOne {
	seuo.mutation.ClearPayload()
	return seuo
}

// SetFailureCount sets the "failure_count" field.
func (seuo *SystemEventUpdateOne) SetFailureCount(i int) *SystemEventUpdateOne {
	seuo.mutation.ResetFailureCount()
	seuo.mutation.SetFailureCount(i)
	return seuo
}

// SetNillableFailureCount sets the "failure_count" field if the given value is not nil.
func (seuo *SystemEventUpdateOne) SetNillableFailureCount(i *int) *SystemEventUpdateOne {
	if i != nil {
		seuo.SetFailureCount(*i)
	}
	return seuo
}

// AddFailureCount adds i to the "failure_count" field.
func (seuo *SystemEventUpdateOne) AddFailureCount(i int) *SystemEventUpdateOne {
	seuo.mutation.AddFailureCount(i)
	return seuo
}

// SetFailureReason sets the "failure_reason" field.
func (seuo *SystemEventUpdateOne) SetFailureReason(s string) *SystemEventUpdateOne {
	seuo.mutation.SetFailureReason(s)
	return seuo
}

// SetNillableFailureReason sets the "failure_reason" field if the given value is not nil.
func (seuo *SystemEventUpdateOne) SetNillableFailureReason(s *string) *SystemEventUpdateOne {
	if s != nil {
		seuo.SetFailureReason(*s)
	}
	return seuo
}

// ClearFailureReason clears the value of the "failure_reason" field.
func (seuo *SystemEventUpdateOne) ClearFailureReason() *SystemEventUpdateOne {
	seuo.mutation.ClearFailureReason()
	return seuo
}

// Mutation returns the SystemEventMutation object of the builder.
func (seuo *SystemEventUpdateOne) Mutation() *SystemEventMutation {
	return seuo.mutation
}

// Where appends a list predicates to the SystemEventUpdate builder.
func (seuo *SystemEventUpdateOne) Where(ps ...predicate.SystemEvent) *SystemEventUpdateOne {
	seuo.mutation.Where(ps...)
	return seuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (seuo *SystemEventUpdateOne) Select(field string, fields ...string) *SystemEventUpdateOne {
	seuo.fields = append([]string{field}, fields...)
	return seuo
}

// Save executes the query and returns the updated SystemEvent entity.
func (seuo *SystemEventUpdateOne) Save(ctx context.Context) (*SystemEvent, error) {
	seuo.defaults()
	return withHooks(ctx, seuo.sqlSave, seuo.mutation, seuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (seuo *SystemEventUpdateOne) SaveX(ctx context.Context) *SystemEvent {
	node, err := seuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (seuo *SystemEventUpdateOne) Exec(ctx context.Context) error {
	_, err := seuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (seuo *SystemEventUpdateOne) ExecX(ctx context.Context) {
	if err := seuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (seuo *SystemEventUpdateOne) defaults() {
	if _, ok := seuo.mutation.UpdatedAt(); !ok {
		v := systemevent.UpdateDefaultUpdatedAt()
		seuo.mutation.SetUpdatedAt(v)
	}
}

func (seuo *SystemEventUpdateOne) sqlSave(ctx context.Context) (_node *SystemEvent, err error) {
	_spec := sqlgraph.NewUpdateSpec(systemevent.Table, systemevent.Columns, sqlgraph.NewFieldSpec(systemevent.FieldID, field.TypeString))
	id, ok := seuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SystemEvent.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := seuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, systemevent.FieldID)
		for _, f := range fields {
			if !systemevent.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != systemevent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := seuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := seuo.mutation.Status(); ok {
		_spec.SetField(systemevent.FieldStatus, field.TypeString, value)
	}
	if value, ok := seuo.mutation.UpdatedAt(); ok {
		_spec.SetField(systemevent.FieldUpdatedAt, field.TypeTime, value)
	}
	if seuo.mutation.CreatedByCleared() {
		_spec.ClearField(systemevent.FieldCreatedBy, field.TypeString)
	}
	if value, ok := seuo.mutation.UpdatedBy(); ok {
		_spec.SetField(systemevent.FieldUpdatedBy, field.TypeString, value)
	}
	if seuo.mutation.UpdatedByCleared() {
		_spec.ClearField(systemevent.FieldUpdatedBy, field.TypeString)
	}
	if seuo.mutation.EnvironmentIDCleared() {
		_spec.ClearField(systemevent.FieldEnvironmentID, field.TypeString)
	}
	if value, ok := seuo.mutation.EventName(); ok {
		_spec.SetField(systemevent.FieldEventName, field.TypeString, value)
	}
	if seuo.mutation.EventNameCleared() {
		_spec.ClearField(systemevent.FieldEventName, field.TypeString)
	}
	if value, ok := seuo.mutation.EntityType(); ok {
		_spec.SetField(systemevent.FieldEntityType, field.TypeString, value)
	}
	if seuo.mutation.EntityTypeCleared() {
		_spec.ClearField(systemevent.FieldEntityType, field.TypeString)
	}
	if value, ok := seuo.mutation.EntityID(); ok {
		_spec.SetField(systemevent.FieldEntityID, field.TypeString, value)
	}
	if seuo.mutation.EntityIDCleared() {
		_spec.ClearField(systemevent.FieldEntityID, field.TypeString)
	}
	if value, ok := seuo.mutation.WebhookMessageID(); ok {
		_spec.SetField(systemevent.FieldWebhookMessageID, field.TypeString, value)
	}
	if seuo.mutation.WebhookMessageIDCleared() {
		_spec.ClearField(systemevent.FieldWebhookMessageID, field.TypeString)
	}
	if value, ok := seuo.mutation.PublishedAt(); ok {
		_spec.SetField(systemevent.FieldPublishedAt, field.TypeTime, value)
	}
	if seuo.mutation.PublishedAtCleared() {
		_spec.ClearField(systemevent.FieldPublishedAt, field.TypeTime)
	}
	if value, ok := seuo.mutation.Payload(); ok {
		_spec.SetField(systemevent.FieldPayload, field.TypeJSON, value)
	}
	if seuo.mutation.PayloadCleared() {
		_spec.ClearField(systemevent.FieldPayload, field.TypeJSON)
	}
	if value, ok := seuo.mutation.FailureCount(); ok {
		_spec.SetField(systemevent.FieldFailureCount, field.TypeInt, value)
	}
	if value, ok := seuo.mutation.AddedFailureCount(); ok {
		_spec.AddField(systemevent.FieldFailureCount, field.TypeInt, value)
	}
	if value, ok := seuo.mutation.FailureReason(); ok {
		_spec.SetField(systemevent.FieldFailureReason, field.TypeString, value)
	}
	if seuo.mutation.FailureReasonCleared() {
		_spec.ClearField(systemevent.FieldFailureReason, field.TypeString)
	}
	_node = &SystemEvent{config: seuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, seuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{systemevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	seuo.mutation.done = true
	return _node, nil
}
