// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/flexprice/flexprice/ent/systemevent"
)

// SystemEventCreate is the builder for creating a SystemEvent entity.
type SystemEventCreate struct {
	config
	mutation *SystemEventMutation
	hooks    []Hook
}

// SetTenantID sets the "tenant_id" field.
func (sec *SystemEventCreate) SetTenantID(s string) *SystemEventCreate {
	sec.mutation.SetTenantID(s)
	return sec
}

// SetStatus sets the "status" field.
func (sec *SystemEventCreate) SetStatus(s string) *SystemEventCreate {
	sec.mutation.SetStatus(s)
	return sec
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (sec *SystemEventCreate) SetNillableStatus(s *string) *SystemEventCreate {
	if s != nil {
		sec.SetStatus(*s)
	}
	return sec
}

// SetCreatedAt sets the "created_at" field.
func (sec *SystemEventCreate) SetCreatedAt(t time.Time) *SystemEventCreate {
	sec.mutation.SetCreatedAt(t)
	return sec
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (sec *SystemEventCreate) SetNillableCreatedAt(t *time.Time) *SystemEventCreate {
	if t != nil {
		sec.SetCreatedAt(*t)
	}
	return sec
}

// SetUpdatedAt sets the "updated_at" field.
func (sec *SystemEventCreate) SetUpdatedAt(t time.Time) *SystemEventCreate {
	sec.mutation.SetUpdatedAt(t)
	return sec
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (sec *SystemEventCreate) SetNillableUpdatedAt(t *time.Time) *SystemEventCreate {
	if t != nil {
		sec.SetUpdatedAt(*t)
	}
	return sec
}

// SetCreatedBy sets the "created_by" field.
func (sec *SystemEventCreate) SetCreatedBy(s string) *SystemEventCreate {
	sec.mutation.SetCreatedBy(s)
	return sec
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (sec *SystemEventCreate) SetNillableCreatedBy(s *string) *SystemEventCreate {
	if s != nil {
		sec.SetCreatedBy(*s)
	}
	return sec
}

// SetUpdatedBy sets the "updated_by" field.
func (sec *SystemEventCreate) SetUpdatedBy(s string) *SystemEventCreate {
	sec.mutation.SetUpdatedBy(s)
	return sec
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (sec *SystemEventCreate) SetNillableUpdatedBy(s *string) *SystemEventCreate {
	if s != nil {
		sec.SetUpdatedBy(*s)
	}
	return sec
}

// SetEnvironmentID sets the "environment_id" field.
func (sec *SystemEventCreate) SetEnvironmentID(s string) *SystemEventCreate {
	sec.mutation.SetEnvironmentID(s)
	return sec
}

// SetNillableEnvironmentID sets the "environment_id" field if the given value is not nil.
func (sec *SystemEventCreate) SetNillableEnvironmentID(s *string) *SystemEventCreate {
	if s != nil {
		sec.SetEnvironmentID(*s)
	}
	return sec
}

// SetEventName sets the "event_name" field.
func (sec *SystemEventCreate) SetEventName(s string) *SystemEventCreate {
	sec.mutation.SetEventName(s)
	return sec
}

// SetNillableEventName sets the "event_name" field if the given value is not nil.
func (sec *SystemEventCreate) SetNillableEventName(s *string) *SystemEventCreate {
	if s != nil {
		sec.SetEventName(*s)
	}
	return sec
}

// SetEntityType sets the "entity_type" field.
func (sec *SystemEventCreate) SetEntityType(s string) *SystemEventCreate {
	sec.mutation.SetEntityType(s)
	return sec
}

// SetNillableEntityType sets the "entity_type" field if the given value is not nil.
func (sec *SystemEventCreate) SetNillableEntityType(s *string) *SystemEventCreate {
	if s != nil {
		sec.SetEntityType(*s)
	}
	return sec
}

// SetEntityID sets the "entity_id" field.
func (sec *SystemEventCreate) SetEntityID(s string) *SystemEventCreate {
	sec.mutation.SetEntityID(s)
	return sec
}

// SetNillableEntityID sets the "entity_id" field if the given value is not nil.
func (sec *SystemEventCreate) SetNillableEntityID(s *string) *SystemEventCreate {
	if s != nil {
		sec.SetEntityID(*s)
	}
	return sec
}

// SetWebhookMessageID sets the "webhook_message_id" field.
func (sec *SystemEventCreate) SetWebhookMessageID(s string) *SystemEventCreate {
	sec.mutation.SetWebhookMessageID(s)
	return sec
}

// SetNillableWebhookMessageID sets the "webhook_message_id" field if the given value is not nil.
func (sec *SystemEventCreate) SetNillableWebhookMessageID(s *string) *SystemEventCreate {
	if s != nil {
		sec.SetWebhookMessageID(*s)
	}
	return sec
}

// SetPublishedAt sets the "published_at" field.
func (sec *SystemEventCreate) SetPublishedAt(t time.Time) *SystemEventCreate {
	sec.mutation.SetPublishedAt(t)
	return sec
}

// SetNillablePublishedAt sets the "published_at" field if the given value is not nil.
func (sec *SystemEventCreate) SetNillablePublishedAt(t *time.Time) *SystemEventCreate {
	if t != nil {
		sec.SetPublishedAt(*t)
	}
	return sec
}

// SetPayload sets the "payload" field.
func (sec *SystemEventCreate) SetPayload(m map[string]interface{}) *SystemEventCreate {
	sec.mutation.SetPayload(m)
	return sec
}

// SetFailureCount sets the "failure_count" field.
func (sec *SystemEventCreate) SetFailureCount(i int) *SystemEventCreate {
	sec.mutation.SetFailureCount(i)
	return sec
}

// SetNillableFailureCount sets the "failure_count" field if the given value is not nil.
func (sec *SystemEventCreate) SetNillableFailureCount(i *int) *SystemEventCreate {
	if i != nil {
		sec.SetFailureCount(*i)
	}
	return sec
}

// SetFailureReason sets the "failure_reason" field.
func (sec *SystemEventCreate) SetFailureReason(s string) *SystemEventCreate {
	sec.mutation.SetFailureReason(s)
	return sec
}

// SetNillableFailureReason sets the "failure_reason" field if the given value is not nil.
func (sec *SystemEventCreate) SetNillableFailureReason(s *string) *SystemEventCreate {
	if s != nil {
		sec.SetFailureReason(*s)
	}
	return sec
}

// SetID sets the "id" field.
func (sec *SystemEventCreate) SetID(s string) *SystemEventCreate {
	sec.mutation.SetID(s)
	return sec
}

// Mutation returns the SystemEventMutation object of the builder.
func (sec *SystemEventCreate) Mutation() *SystemEventMutation {
	return sec.mutation
}

// Save creates the SystemEvent in the database.
func (sec *SystemEventCreate) Save(ctx context.Context) (*SystemEvent, error) {
	sec.defaults()
	return withHooks(ctx, sec.sqlSave, sec.mutation, sec.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (sec *SystemEventCreate) SaveX(ctx context.Context) *SystemEvent {
	v, err := sec.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (sec *SystemEventCreate) Exec(ctx context.Context) error {
	_, err := sec.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sec *SystemEventCreate) ExecX(ctx context.Context) {
	if err := sec.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (sec *SystemEventCreate) defaults() {
	if _, ok := sec.mutation.Status(); !ok {
		v := systemevent.DefaultStatus
		sec.mutation.SetStatus(v)
	}
	if _, ok := sec.mutation.CreatedAt(); !ok {
		v := systemevent.DefaultCreatedAt()
		sec.mutation.SetCreatedAt(v)
	}
	if _, ok := sec.mutation.UpdatedAt(); !ok {
		v := systemevent.DefaultUpdatedAt()
		sec.mutation.SetUpdatedAt(v)
	}
	if _, ok := sec.mutation.EnvironmentID(); !ok {
		v := systemevent.DefaultEnvironmentID
		sec.mutation.SetEnvironmentID(v)
	}
	if _, ok := sec.mutation.EventName(); !ok {
		v := systemevent.DefaultEventName
		sec.mutation.SetEventName(v)
	}
	if _, ok := sec.mutation.EntityType(); !ok {
		v := systemevent.DefaultEntityType
		sec.mutation.SetEntityType(v)
	}
	if _, ok := sec.mutation.EntityID(); !ok {
		v := systemevent.DefaultEntityID
		sec.mutation.SetEntityID(v)
	}
	if _, ok := sec.mutation.FailureCount(); !ok {
		v := systemevent.DefaultFailureCount
		sec.mutation.SetFailureCount(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (sec *SystemEventCreate) check() error {
	if _, ok := sec.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "SystemEvent.tenant_id"`)}
	}
	if v, ok := sec.mutation.TenantID(); ok {
		if err := systemevent.TenantIDValidator(v); err != nil {
			return &ValidationError{Name: "tenant_id", err: fmt.Errorf(`ent: validator failed for field "SystemEvent.tenant_id": %w`, err)}
		}
	}
	if _, ok := sec.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "SystemEvent.status"`)}
	}
	if _, ok := sec.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "SystemEvent.created_at"`)}
	}
	if _, ok := sec.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "SystemEvent.updated_at"`)}
	}
	if _, ok := sec.mutation.FailureCount(); !ok {
		return &ValidationError{Name: "failure_count", err: errors.New(`ent: missing required field "SystemEvent.failure_count"`)}
	}
	return nil
}

func (sec *SystemEventCreate) sqlSave(ctx context.Context) (*SystemEvent, error) {
	if err := sec.check(); err != nil {
		return nil, err
	}
	_node, _spec := sec.createSpec()
	if err := sqlgraph.CreateNode(ctx, sec.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected SystemEvent.ID type: %T", _spec.ID.Value)
		}
	}
	sec.mutation.id = &_node.ID
	sec.mutation.done = true
	return _node, nil
}

func (sec *SystemEventCreate) createSpec() (*SystemEvent, *sqlgraph.CreateSpec) {
	var (
		_node = &SystemEvent{config: sec.config}
		_spec = sqlgraph.NewCreateSpec(systemevent.Table, sqlgraph.NewFieldSpec(systemevent.FieldID, field.TypeString))
	)
	if id, ok := sec.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := sec.mutation.TenantID(); ok {
		_spec.SetField(systemevent.FieldTenantID, field.TypeString, value)
		_node.TenantID = value
	}
	if value, ok := sec.mutation.Status(); ok {
		_spec.SetField(systemevent.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := sec.mutation.CreatedAt(); ok {
		_spec.SetField(systemevent.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := sec.mutation.UpdatedAt(); ok {
		_spec.SetField(systemevent.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := sec.mutation.CreatedBy(); ok {
		_spec.SetField(systemevent.FieldCreatedBy, field.TypeString, value)
		_node.CreatedBy = value
	}
	if value, ok := sec.mutation.UpdatedBy(); ok {
		_spec.SetField(systemevent.FieldUpdatedBy, field.TypeString, value)
		_node.UpdatedBy = value
	}
	if value, ok := sec.mutation.EnvironmentID(); ok {
		_spec.SetField(systemevent.FieldEnvironmentID, field.TypeString, value)
		_node.EnvironmentID = value
	}
	if value, ok := sec.mutation.EventName(); ok {
		_spec.SetField(systemevent.FieldEventName, field.TypeString, value)
		_node.EventName = value
	}
	if value, ok := sec.mutation.EntityType(); ok {
		_spec.SetField(systemevent.FieldEntityType, field.TypeString, value)
		_node.EntityType = value
	}
	if value, ok := sec.mutation.EntityID(); ok {
		_spec.SetField(systemevent.FieldEntityID, field.TypeString, value)
		_node.EntityID = value
	}
	if value, ok := sec.mutation.WebhookMessageID(); ok {
		_spec.SetField(systemevent.FieldWebhookMessageID, field.TypeString, value)
		_node.WebhookMessageID = &value
	}
	if value, ok := sec.mutation.PublishedAt(); ok {
		_spec.SetField(systemevent.FieldPublishedAt, field.TypeTime, value)
		_node.PublishedAt = &value
	}
	if value, ok := sec.mutation.Payload(); ok {
		_spec.SetField(systemevent.FieldPayload, field.TypeJSON, value)
		_node.Payload = value
	}
	if value, ok := sec.mutation.FailureCount(); ok {
		_spec.SetField(systemevent.FieldFailureCount, field.TypeInt, value)
		_node.FailureCount = value
	}
	if value, ok := sec.mutation.FailureReason(); ok {
		_spec.SetField(systemevent.FieldFailureReason, field.TypeString, value)
		_node.FailureReason = &value
	}
	return _node, _spec
}

// SystemEventCreateBulk is the builder for creating many SystemEvent entities in bulk.
type SystemEventCreateBulk struct {
	config
	err      error
	builders []*SystemEventCreate
}

// Save creates the SystemEvent entities in the database.
func (secb *SystemEventCreateBulk) Save(ctx context.Context) ([]*SystemEvent, error) {
	if secb.err != nil {
		return nil, secb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(secb.builders))
	nodes := make([]*SystemEvent, len(secb.builders))
	mutators := make([]Mutator, len(secb.builders))
	for i := range secb.builders {
		func(i int, root context.Context) {
			builder := secb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SystemEventMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, secb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, secb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, secb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (secb *SystemEventCreateBulk) SaveX(ctx context.Context) []*SystemEvent {
	v, err := secb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (secb *SystemEventCreateBulk) Exec(ctx context.Context) error {
	_, err := secb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (secb *SystemEventCreateBulk) ExecX(ctx context.Context) {
	if err := secb.Exec(ctx); err != nil {
		panic(err)
	}
}
